language: python
python:
  - "2.7"
install:
  - npm install
  - bower install
  - pip install -r requirements.txt
  - make
script:
  - nosetests
  - python setup.py build
before_install:
  - pip install codecov
after_success:
  - codecov
