language: python
dist: precise

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
install:
  - make python_packages
  - make python_dev_packages
  - make
script:
  - tox -e $TOX_ENV
  - make test
before_install:
  - pip install codecov
after_success:
  - codecov
